management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: '1.0'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
      
pkis:
  BamPKI:
    endpoint: "https://gateway-test.baridesign.ma/gateway/api/"
    certificatePath: "/home/mohammed/Documents/Digiup/Projects/iMDAE/service-dcc/src/main/resources/certificates/20562-Classe1__Authentification.p12"
    keyPassword:
keyStore:
  path: "/home/mohammed/Documents/Digiup/cacerts"
  keyStorePassword:
