realms:
  value: "imdae-ms"

auth:
  client-id: "imdae-ms-auth"
  client-secret: "G047Bkz3BSkTTpHx604p79pFUYLLcfId"
  grant_type: "client_credentials"
spring:
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
  sleuth:
    sampler:
      probability: '1.0'
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@${EUREKA_HOST:localhost}:8761/eureka
      
# Actuator Prometheus Endpoint
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  health:
    circuitbreakers:
      enabled: true

      
resilience4j:
  circuitbreaker:
    instances:
      service_auth:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      service_auth:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 10s
  ratelimiter:
    instances:
      service_auth:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
