mongodb:
  imdae:
    authentication-database: admin
    username: ${MONGODB_USERNAME:root}
    database: ${MONGODB_DATABASE:imdae}
    password: ${MONGODB_PASSWORD:password}
    port: ${MONGODB_PORT:27017}
    host: ${MONGODB_DOMAIN:10.107.225.60}
  gateway:
    authentication-database: admin
    username: ${MONGODB_USERNAME:root}
    database: ${MONGODB_DATABASE:getewayClient}
    password: ${MONGODB_PASSWORD:password}
    port: ${MONGODB_PORT:27017}
    host: ${MONGODB_DOMAIN:10.107.225.60}
spring:
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
  sleuth:
    sampler:
      probability: '1.0'

test:
  name: "hello micro service updated config data againe"
saving:
  default:
    path: ${SAVING_DEFAULT_PATH:/home/mohammed/docker_data/}
bam: 
  ssl-keystore-path: ${SSL_KEYSTORE_PATH:/data/BaridMedia_Client_Authentification.p12}
  
  
springdoc:
  swagger-ui:
    config-url: /v3/api-docs/
