
spring:
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGODB_USERNAME:root}
      database: ${MONGODB_DATABASE:imdae}
      password: ${MONGODB_PASSWORD:password}
      port:     ${MONGODB_PORT:27017}
      host:     ${MONGODB_DOMAIN:localhost}
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: '1.0'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
